include ../../common/common_mak
LibBaseName = clemmatiser

object_base_names = clemmatiser

libs = ../../AgramtabLib/libAgramtab$(ct).$(lib_ext)       \
       ../../GraphanLib/libGraphan$(ct).$(lib_ext)         \
       ../../LemmatizerLib/libLemmatizer$(ct).$(lib_ext)   \
       ../../MorphWizardLib/libMorphWizard$(ct).$(lib_ext) \
       ../../StructDictLib/libStructDict$(ct).$(lib_ext)   \
       ../cpp/libSimpleLemmatiser$(ct).$(lib_ext)

include ../../common/common_lib_mak

