include ../../common/common_mak
LibName=libSimpleLemmatiser$(ct)

objects=SimpleLemmatiser.o$(ct) \
        CMorphology.o$(ct)      \
        LemInterface.o$(ct)     \
        converts.o$(ct)         \
        utf_cp.o$(ct)

libs=../../LemmatizerLib/libLemmatizer$(ct).$(lib_ext)    \
      ../../AgramtabLib/libAgramtab$(ct).$(lib_ext)       \
      ../../GraphanLib/libGraphan$(ct).$(lib_ext)         \
      ../../MorphWizardLib/libMorphWizard$(ct).$(lib_ext) \
      ../../StructDictLib/libStructDict$(ct).$(lib_ext)

include ../../common/common_lib_mak

