include ../common/common_mak
LibBaseName = Agramtab


object_base_names = EngGramTab \
	  	    GerGramTab \
		    RusGramTab \
		    agramtab_ \
		    ../common/utilit

include ../common/common_lib_mak
