include ../common/common_mak
VPATH = ../
LibBaseName = Graphan

object_base_names = C_desc \
		    Consent \
		    Cs_hiera \
		    GraphmatFile \
		    HtmlConv \
		    Nc_desc \
		    Writegra \
		    abbrev \
		    graline \
		    Oborots \
		    UnitHolder \
		    GraphanDicts \
		    Sentences \
		    ../common/utilit

libs = ../StructDictLib/libStructDict$(ct).$(lib_ext)

include ../common/common_lib_mak
